# Generated by Django 4.2.2 on 2023-12-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.ImageField(upload_to='imagenes/')),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
